/**
 * @module AetherWorld
 *
 * High-level TypeScript wrapper around the Wasm physics world.
 * Handles Wasm module lifecycle, buffer management, and provides
 * a developer-friendly API.
 */

import type {
  Vec3, Quat, ShapeDescriptor, BodyOptions, WorldConfig,
  BodyState, StepMetrics,
} from './types.js';
import { PHI } from './types.js';

/** Raw Wasm module interface (generated by wasm-bindgen) */
interface AetherWasmModule {
  AetherWorld: {
    new(): WasmWorld;
    withGravity(gx: number, gy: number, gz: number): WasmWorld;
  };
}

interface WasmWorld {
  step(dt: number): void;
  createSphere(radius: number, mass: number): number;
  createCuboid(hx: number, hy: number, hz: number, mass: number): number;
  createCapsule(halfHeight: number, radius: number, mass: number): number;
  createGroundPlane(yOffset: number): number;
  createStaticCuboid(hx: number, hy: number, hz: number): number;
  setPosition(id: number, x: number, y: number, z: number): void;
  setVelocity(id: number, vx: number, vy: number, vz: number): void;
  applyForce(id: number, fx: number, fy: number, fz: number): void;
  applyImpulse(id: number, ix: number, iy: number, iz: number): void;
  getPosition(id: number): Float64Array;
  getOrientation(id: number): Float64Array;
  getVelocity(id: number): Float64Array;
  getAllPositions(): Float64Array;
  getAllOrientations(): Float64Array;
  bodyCount(): number;
  activeBodyCount(): number;
  getTime(): number;
  readonly frame: number;
  readonly phi: number;
  free(): void;
}

/**
 * AetherWorld — The main physics simulation interface.
 *
 * Usage:
 * ```ts
 * const world = await AetherWorld.create({ gravity: { x: 0, y: -9.81, z: 0 } });
 * const ball = world.createBody({ type: 'sphere', radius: 0.5 }, { mass: 1, position: { x: 0, y: 10, z: 0 } });
 * world.step(1 / 60);
 * const pos = world.getPosition(ball);
 * ```
 */
export class AetherWorld {
  private wasm: WasmWorld;
  private _stepMetrics: StepMetrics = {
    stepTimeMs: 0, bodyCount: 0, activeBodyCount: 0, constraintCount: 0, frame: 0,
  };
  private bodyMetadata: Map<number, { shape: ShapeDescriptor; userData: unknown }> = new Map();

  private constructor(wasm: WasmWorld) {
    this.wasm = wasm;
  }

  /**
   * Create a new AetherWorld by loading the Wasm module.
   * @param config - World configuration
   * @param wasmPath - Path to the .wasm file (default: auto-detect)
   */
  static async create(config: WorldConfig = {}, wasmPath?: string): Promise<AetherWorld> {
    const path = wasmPath ?? new URL('./aether_wasm_bg.wasm', import.meta.url).href;
    const module: AetherWasmModule = await import(path);
    const g = config.gravity ?? { x: 0, y: -9.80665, z: 0 };
    const wasmWorld = module.AetherWorld.withGravity(g.x, g.y, g.z);
    return new AetherWorld(wasmWorld);
  }

  /**
   * Create from an already-initialized Wasm module (for testing/SSR).
   */
  static fromWasm(wasm: WasmWorld): AetherWorld {
    return new AetherWorld(wasm);
  }

  /**
   * Create a dynamic body with the given shape and options.
   */
  createBody(shape: ShapeDescriptor, options: BodyOptions = {}): number {
    const mass = options.mass ?? PHI; // Default mass = φ
    let id: number;

    switch (shape.type) {
      case 'sphere':
        id = this.wasm.createSphere(shape.radius, mass);
        break;
      case 'cuboid':
        id = this.wasm.createCuboid(
          shape.halfExtents.x, shape.halfExtents.y, shape.halfExtents.z, mass,
        );
        break;
      case 'capsule':
        id = this.wasm.createCapsule(shape.halfHeight, shape.radius, mass);
        break;
      case 'plane':
        id = this.wasm.createGroundPlane(shape.offset);
        break;
      default:
        throw new Error(`Unknown shape type: ${(shape as ShapeDescriptor).type}`);
    }

    if (options.position) {
      this.wasm.setPosition(id, options.position.x, options.position.y, options.position.z);
    }
    if (options.velocity) {
      this.wasm.setVelocity(id, options.velocity.x, options.velocity.y, options.velocity.z);
    }

    this.bodyMetadata.set(id, { shape, userData: options.userData });
    return id;
  }

  /**
   * Create a static body (ground, walls, platforms).
   */
  createStatic(shape: ShapeDescriptor, position?: Vec3): number {
    let id: number;
    switch (shape.type) {
      case 'plane':
        id = this.wasm.createGroundPlane(shape.offset);
        break;
      case 'cuboid':
        id = this.wasm.createStaticCuboid(
          shape.halfExtents.x, shape.halfExtents.y, shape.halfExtents.z,
        );
        break;
      default:
        throw new Error(`Static bodies only support 'plane' and 'cuboid' shapes`);
    }
    if (position) {
      this.wasm.setPosition(id, position.x, position.y, position.z);
    }
    this.bodyMetadata.set(id, { shape, userData: null });
    return id;
  }

  /** Step the simulation forward by dt seconds. */
  step(dt: number): StepMetrics {
    const start = performance.now();
    this.wasm.step(dt);
    this._stepMetrics = {
      stepTimeMs: performance.now() - start,
      bodyCount: this.wasm.bodyCount(),
      activeBodyCount: this.wasm.activeBodyCount(),
      constraintCount: 0, // TODO: expose from Wasm
      frame: Number(this.wasm.frame),
    };
    return this._stepMetrics;
  }

  /** Get a body's position. */
  getPosition(id: number): Vec3 {
    const p = this.wasm.getPosition(id);
    return { x: p[0], y: p[1], z: p[2] };
  }

  /** Get a body's orientation. */
  getOrientation(id: number): Quat {
    const q = this.wasm.getOrientation(id);
    return { x: q[0], y: q[1], z: q[2], w: q[3] };
  }

  /** Get a body's linear velocity. */
  getVelocity(id: number): Vec3 {
    const v = this.wasm.getVelocity(id);
    return { x: v[0], y: v[1], z: v[2] };
  }

  /** Set a body's position. */
  setPosition(id: number, pos: Vec3): void {
    this.wasm.setPosition(id, pos.x, pos.y, pos.z);
  }

  /** Set a body's velocity. */
  setVelocity(id: number, vel: Vec3): void {
    this.wasm.setVelocity(id, vel.x, vel.y, vel.z);
  }

  /** Apply a force to a body (accumulated for the current step). */
  applyForce(id: number, force: Vec3): void {
    this.wasm.applyForce(id, force.x, force.y, force.z);
  }

  /** Apply an impulse to a body (immediate velocity change). */
  applyImpulse(id: number, impulse: Vec3): void {
    this.wasm.applyImpulse(id, impulse.x, impulse.y, impulse.z);
  }

  /**
   * Get ALL body positions as a flat array [x0,y0,z0, x1,y1,z1, ...].
   * Optimized for bulk transfer to rendering engines.
   */
  getAllPositions(): Float64Array {
    return this.wasm.getAllPositions();
  }

  /** Get ALL orientations as flat [x0,y0,z0,w0, x1,y1,z1,w1, ...]. */
  getAllOrientations(): Float64Array {
    return this.wasm.getAllOrientations();
  }

  /** Get the state of a single body. */
  getBodyState(id: number): BodyState {
    return {
      id,
      position: this.getPosition(id),
      orientation: this.getOrientation(id),
      velocity: this.getVelocity(id),
      sleeping: false, // TODO: expose from Wasm
    };
  }

  /** Last step performance metrics. */
  get metrics(): StepMetrics { return this._stepMetrics; }

  /** Total body count. */
  get bodyCount(): number { return this.wasm.bodyCount(); }

  /** Simulation time. */
  get time(): number { return this.wasm.getTime(); }

  /** The golden ratio — the fundamental constant. */
  static get PHI(): number { return PHI; }

  /** Free Wasm memory. Call when disposing the world. */
  dispose(): void {
    this.wasm.free();
    this.bodyMetadata.clear();
  }
}
